# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  batch: true
  branches:
    include:
      - master
      - azure-*

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build image
      inputs:
        containerRegistry: 'dockerhub-nhsy'
        repository: 'dizzyplan/gcp-devops'
        command: 'buildAndPush'

        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
