# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  batch: true
  branches:
    include:
      - master
      - azure-*

resources:
- repo: self

variables:
  registry: 'dockerhub-nhsy'
  repository: 'dizzyplan/gcp-devops'
  tf_0.12_version: '0.12.29'
  tf_0.13_version: '0.13.5'
  tf_0.14_version: '0.14.1'

stages:
- stage: Build
  displayName: Build images
  jobs:  
  - job: Build
    displayName: Build terraform 0.12.x image
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build
      inputs:
        containerRegistry: $(registry)
        repository: $(repository)
        command: 'build'
        arguments: '--build-arg TERRAFORM_VERSION=$(tf_0.12_version)'
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tf_0.12_version)
    - task: Docker@2
      displayName: Push
      inputs:
        containerRegistry: $(registry)
        repository: $(repository)
        command: 'build'
        tags: |
          $(tf_0.12_version)

  - job: Build
    displayName: Build terraform 0.12.x image
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build
      inputs:
        containerRegistry: $(registry)
        repository: $(repository)
        command: 'build'
        arguments: '--build-arg TERRAFORM_VERSION=$(tf_0.13_version)'
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tf_0.13_version)
    - task: Docker@2
      displayName: Push
      inputs:
        containerRegistry: $(registry)
        repository: $(repository)
        command: 'build'
        tags: |
          $(tf_0.13_version)