# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  batch: true
  branches:
    include:
      - master
      - azure-*

resources:
- repo: self


variables:
  tf_0.12_version: '0.12.29'
  tf_0.13_version: '0.13.5'
  tf_0.14_version: '0.14.1'

stages:
- stage: Build
  displayName: Build images
  jobs:  
  - job: Build
    displayName: Build terraform $(tf_0.12_version) image
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build terraform 0.12.x image
      inputs:
        containerRegistry: 'dockerhub-nhsy'
        repository: 'dizzyplan/gcp-devops'
        command: 'buildAndPush'
        arguments: '--build-arg TERRAFORM_VERSION=$(tf_0.12_version)'
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tf_0.12_version)
